/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazCliente;

import java.util.List;
import javax.swing.DefaultListModel;
import rmi.SimulacionRemota;

/**
 *
 * @author unaih
 */
public class InterfazCliente extends javax.swing.JFrame {

    private DefaultListModel<String> modeloRankingZombis = new DefaultListModel<>();
    private rmi.SimulacionRemota simulacion;

    /**
     * Creates new form InterfazCliente
     */
    public InterfazCliente() {
        initComponents();
        ListaZ.setModel(modeloRankingZombis);
        try {
            simulacion = (rmi.SimulacionRemota) java.rmi.Naming.lookup("//localhost/SimulacionZombis");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo conectar al servidor: " + e.getMessage());
            System.exit(1);
        }
        javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
            try {
                int nRefugio = simulacion.getNumeroHumanosRefugio();
                java.util.List<Integer> tuneles = simulacion.getNumeroHumanosTuneles();
                java.util.List<Integer> riesgoH = simulacion.getNumeroHumanosZonasRiesgo();
                java.util.List<Integer> riesgoZ = simulacion.getNumeroZombisZonasRiesgo();
                java.util.List<String> ranking = simulacion.getZombisMasLetales();

                actualizarNumeros(nRefugio, tuneles, riesgoH, riesgoZ);
                actualizarRanking(ranking);
            } catch (Exception ex) {
                // Manejo de error de conexión
            }
        });
        timer.start();
    }

    public void actualizarNumeros(
            int numRefugio,
            List<Integer> tuneles,
            List<Integer> zonas,
            List<Integer> zombis
    ) {
        nRefugio.setText(String.valueOf(numRefugio));
        nRefugio.setText(String.valueOf(numRefugio));
        nTunel1.setText(String.valueOf(tuneles.get(0)));
        nTunel2.setText(String.valueOf(tuneles.get(1)));
        nTunel3.setText(String.valueOf(tuneles.get(2)));
        nTunel4.setText(String.valueOf(tuneles.get(3)));
        nRiesgoH1.setText(String.valueOf(zonas.get(0)));
        nRiesgoH2.setText(String.valueOf(zonas.get(1)));
        nRiesgoH3.setText(String.valueOf(zonas.get(2)));
        nRiesgoH4.setText(String.valueOf(zonas.get(3)));
        nRiesgoZ1.setText(String.valueOf(zombis.get(0)));
        nRiesgoZ2.setText(String.valueOf(zombis.get(1)));
        nRiesgoZ3.setText(String.valueOf(zombis.get(2)));
        nRiesgoZ4.setText(String.valueOf(zombis.get(3)));
    }

    public void actualizarRanking(List<String> ranking) {
        modeloRankingZombis.clear();
        for (String zombi : ranking) {
            modeloRankingZombis.addElement(zombi);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        Base = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        nRefugio = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        nTunel1 = new javax.swing.JLabel();
        nTunel2 = new javax.swing.JLabel();
        nTunel4 = new javax.swing.JLabel();
        nTunel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        nRiesgoH1 = new javax.swing.JLabel();
        nRiesgoH2 = new javax.swing.JLabel();
        nRiesgoH3 = new javax.swing.JLabel();
        nRiesgoH4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        nRiesgoZ1 = new javax.swing.JLabel();
        nRiesgoZ2 = new javax.swing.JLabel();
        nRiesgoZ3 = new javax.swing.JLabel();
        nRiesgoZ4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        Detener = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaZ = new javax.swing.JList<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Base.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("Número de humanos en el refugio");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        nRefugio.setBackground(new java.awt.Color(255, 255, 255));
        nRefugio.setForeground(new java.awt.Color(0, 0, 0));
        nRefugio.setText("jLabel1");
        nRefugio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setText("Número de humanos en los túneles");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        nTunel1.setBackground(new java.awt.Color(255, 255, 255));
        nTunel1.setForeground(new java.awt.Color(0, 0, 0));
        nTunel1.setText("jLabel1");
        nTunel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nTunel2.setBackground(new java.awt.Color(255, 255, 255));
        nTunel2.setForeground(new java.awt.Color(0, 0, 0));
        nTunel2.setText("jLabel1");
        nTunel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nTunel4.setBackground(new java.awt.Color(255, 255, 255));
        nTunel4.setForeground(new java.awt.Color(0, 0, 0));
        nTunel4.setText("jLabel1");
        nTunel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nTunel3.setBackground(new java.awt.Color(255, 255, 255));
        nTunel3.setForeground(new java.awt.Color(0, 0, 0));
        nTunel3.setText("jLabel1");
        nTunel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.setText("Número de humanos en zonas riesgo");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        nRiesgoH1.setBackground(new java.awt.Color(255, 255, 255));
        nRiesgoH1.setForeground(new java.awt.Color(0, 0, 0));
        nRiesgoH1.setText("jLabel1");
        nRiesgoH1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nRiesgoH2.setBackground(new java.awt.Color(255, 255, 255));
        nRiesgoH2.setForeground(new java.awt.Color(0, 0, 0));
        nRiesgoH2.setText("jLabel1");
        nRiesgoH2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nRiesgoH3.setBackground(new java.awt.Color(255, 255, 255));
        nRiesgoH3.setForeground(new java.awt.Color(0, 0, 0));
        nRiesgoH3.setText("jLabel1");
        nRiesgoH3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nRiesgoH4.setBackground(new java.awt.Color(255, 255, 255));
        nRiesgoH4.setForeground(new java.awt.Color(0, 0, 0));
        nRiesgoH4.setText("jLabel1");
        nRiesgoH4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        jTextField4.setText("Número de zombis en zonas riesgo");
        jTextField4.setBorder(null);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        nRiesgoZ1.setBackground(new java.awt.Color(255, 255, 255));
        nRiesgoZ1.setForeground(new java.awt.Color(0, 0, 0));
        nRiesgoZ1.setText("jLabel1");
        nRiesgoZ1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nRiesgoZ2.setBackground(new java.awt.Color(255, 255, 255));
        nRiesgoZ2.setForeground(new java.awt.Color(0, 0, 0));
        nRiesgoZ2.setText("jLabel1");
        nRiesgoZ2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nRiesgoZ3.setBackground(new java.awt.Color(255, 255, 255));
        nRiesgoZ3.setForeground(new java.awt.Color(0, 0, 0));
        nRiesgoZ3.setText("jLabel1");
        nRiesgoZ3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nRiesgoZ4.setBackground(new java.awt.Color(255, 255, 255));
        nRiesgoZ4.setForeground(new java.awt.Color(0, 0, 0));
        nRiesgoZ4.setText("jLabel1");
        nRiesgoZ4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        jTextField5.setText("Zombis más letales");
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        Detener.setBackground(new java.awt.Color(255, 255, 255));
        Detener.setForeground(new java.awt.Color(0, 0, 0));
        Detener.setText("Detener Ejecución");
        Detener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetenerActionPerformed(evt);
            }
        });

        ListaZ.setBackground(new java.awt.Color(255, 255, 255));
        ListaZ.setForeground(new java.awt.Color(0, 0, 0));
        ListaZ.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(ListaZ);

        javax.swing.GroupLayout BaseLayout = new javax.swing.GroupLayout(Base);
        Base.setLayout(BaseLayout);
        BaseLayout.setHorizontalGroup(
            BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaseLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BaseLayout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(nRiesgoH1)
                        .addGap(18, 18, 18)
                        .addComponent(nRiesgoH2)
                        .addGap(18, 18, 18)
                        .addComponent(nRiesgoH3)
                        .addGap(18, 18, 18)
                        .addComponent(nRiesgoH4))
                    .addGroup(BaseLayout.createSequentialGroup()
                        .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95)
                        .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BaseLayout.createSequentialGroup()
                                .addComponent(nTunel1)
                                .addGap(18, 18, 18)
                                .addComponent(nTunel2)
                                .addGap(18, 18, 18)
                                .addComponent(nTunel3)
                                .addGap(18, 18, 18)
                                .addComponent(nTunel4))
                            .addComponent(nRefugio)))
                    .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(BaseLayout.createSequentialGroup()
                            .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField4)
                                .addComponent(jScrollPane3))
                            .addGap(95, 95, 95)
                            .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(BaseLayout.createSequentialGroup()
                                    .addComponent(nRiesgoZ1)
                                    .addGap(18, 18, 18)
                                    .addComponent(nRiesgoZ2)
                                    .addGap(18, 18, 18)
                                    .addComponent(nRiesgoZ3))
                                .addComponent(Detener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addComponent(nRiesgoZ4))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        BaseLayout.setVerticalGroup(
            BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaseLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nRefugio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nTunel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nTunel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nTunel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nTunel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nRiesgoH1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nRiesgoH2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nRiesgoH3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nRiesgoH4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nRiesgoZ1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nRiesgoZ2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nRiesgoZ3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nRiesgoZ4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Detener, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void DetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetenerActionPerformed
        try {
            simulacion.togglePausa();
            // Opcional: cambia el texto del botón según el estado
            boolean pausado = simulacion.isPausado();
            Detener.setText(pausado ? "Reanudar ejecución" : "Detener ejecución");
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al pausar/reanudar: " + ex.getMessage());
        }
    }//GEN-LAST:event_DetenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Base;
    private javax.swing.JButton Detener;
    private javax.swing.JList<String> ListaZ;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel nRefugio;
    private javax.swing.JLabel nRiesgoH1;
    private javax.swing.JLabel nRiesgoH2;
    private javax.swing.JLabel nRiesgoH3;
    private javax.swing.JLabel nRiesgoH4;
    private javax.swing.JLabel nRiesgoZ1;
    private javax.swing.JLabel nRiesgoZ2;
    private javax.swing.JLabel nRiesgoZ3;
    private javax.swing.JLabel nRiesgoZ4;
    private javax.swing.JLabel nTunel1;
    private javax.swing.JLabel nTunel2;
    private javax.swing.JLabel nTunel3;
    private javax.swing.JLabel nTunel4;
    // End of variables declaration//GEN-END:variables
}
