/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazCliente;

import java.util.List;
import javax.swing.DefaultListModel;
import rmi.SimulacionRemota;

/**
 *
 * @author unaih
 */
public class InterfazCliente extends javax.swing.JFrame {

    private DefaultListModel<String> modeloRankingZombis = new DefaultListModel<>();
    private rmi.SimulacionRemota simulacion;

    /**
     * Creates new form InterfazCliente
     */
    public InterfazCliente() {
        initComponents();
        ListaZ.setModel(modeloRankingZombis);
        try {
            simulacion = (rmi.SimulacionRemota) java.rmi.Naming.lookup("//localhost/SimulacionZombis");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo conectar al servidor: " + e.getMessage());
            System.exit(1);
        }
        javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
            try {
                int nRefugio = simulacion.getNumeroHumanosRefugio();
                java.util.List<Integer> tuneles = simulacion.getNumeroHumanosTuneles();
                java.util.List<Integer> riesgoH = simulacion.getNumeroHumanosZonasRiesgo();
                java.util.List<Integer> riesgoZ = simulacion.getNumeroZombisZonasRiesgo();
                java.util.List<String> ranking = simulacion.getZombisMasLetales();

                actualizarNumeros(nRefugio, tuneles, riesgoH, riesgoZ);
                actualizarRanking(ranking);
            } catch (Exception ex) {
                // Manejo de error de conexión
            }
        });
        timer.start();
        
    }

    public void actualizarNumeros(
            int numRefugio,
            List<Integer> tuneles,
            List<Integer> zonas,
            List<Integer> zombis
    ) {
        nRefugio.setText(String.valueOf(numRefugio));
        nRefugio.setText(String.valueOf(numRefugio));
        nTunel1.setText(String.valueOf(tuneles.get(0)));
        nTunel2.setText(String.valueOf(tuneles.get(1)));
        nTunel3.setText(String.valueOf(tuneles.get(2)));
        nTunel4.setText(String.valueOf(tuneles.get(3)));
        nRiesgoH1.setText(String.valueOf(zonas.get(0)));
        nRiesgoH2.setText(String.valueOf(zonas.get(1)));
        nRiesgoH3.setText(String.valueOf(zonas.get(2)));
        nRiesgoH4.setText(String.valueOf(zonas.get(3)));
        nRiesgoZ1.setText(String.valueOf(zombis.get(0)));
        nRiesgoZ2.setText(String.valueOf(zombis.get(1)));
        nRiesgoZ3.setText(String.valueOf(zombis.get(2)));
        nRiesgoZ4.setText(String.valueOf(zombis.get(3)));
    }

    public void actualizarRanking(List<String> ranking) {
        modeloRankingZombis.clear();
        for (String zombi : ranking) {
            modeloRankingZombis.addElement(zombi);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        Base = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        nRefugio = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        nTunel1 = new javax.swing.JLabel();
        nTunel2 = new javax.swing.JLabel();
        nTunel4 = new javax.swing.JLabel();
        nTunel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        nRiesgoH1 = new javax.swing.JLabel();
        nRiesgoH2 = new javax.swing.JLabel();
        nRiesgoH3 = new javax.swing.JLabel();
        nRiesgoH4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        nRiesgoZ1 = new javax.swing.JLabel();
        nRiesgoZ2 = new javax.swing.JLabel();
        nRiesgoZ3 = new javax.swing.JLabel();
        nRiesgoZ4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        Detener = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaZ = new javax.swing.JList<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Base.setBackground(new java.awt.Color(255, 255, 255));
        Base.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("Número de humanos en el refugio");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        Base.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 67, -1, -1));

        nRefugio.setBackground(new java.awt.Color(255, 255, 255));
        nRefugio.setForeground(new java.awt.Color(0, 0, 0));
        nRefugio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nRefugio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Base.add(nRefugio, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 61, 40, 28));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setText("Número de humanos en los túneles");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        Base.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 113, -1, -1));

        nTunel1.setBackground(new java.awt.Color(255, 255, 255));
        nTunel1.setForeground(new java.awt.Color(0, 0, 0));
        nTunel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nTunel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Base.add(nTunel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 107, 40, 28));

        nTunel2.setBackground(new java.awt.Color(255, 255, 255));
        nTunel2.setForeground(new java.awt.Color(0, 0, 0));
        nTunel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nTunel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Base.add(nTunel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 107, 40, 28));

        nTunel4.setBackground(new java.awt.Color(255, 255, 255));
        nTunel4.setForeground(new java.awt.Color(0, 0, 0));
        nTunel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nTunel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Base.add(nTunel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 107, 40, 28));

        nTunel3.setBackground(new java.awt.Color(255, 255, 255));
        nTunel3.setForeground(new java.awt.Color(0, 0, 0));
        nTunel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nTunel3.setToolTipText("");
        nTunel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Base.add(nTunel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 107, 40, 28));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.setText("Número de humanos en zonas riesgo");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        Base.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 159, -1, -1));

        nRiesgoH1.setBackground(new java.awt.Color(255, 255, 255));
        nRiesgoH1.setForeground(new java.awt.Color(0, 0, 0));
        nRiesgoH1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nRiesgoH1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Base.add(nRiesgoH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 153, 40, 28));

        nRiesgoH2.setBackground(new java.awt.Color(255, 255, 255));
        nRiesgoH2.setForeground(new java.awt.Color(0, 0, 0));
        nRiesgoH2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nRiesgoH2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Base.add(nRiesgoH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 153, 40, 28));

        nRiesgoH3.setBackground(new java.awt.Color(255, 255, 255));
        nRiesgoH3.setForeground(new java.awt.Color(0, 0, 0));
        nRiesgoH3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nRiesgoH3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Base.add(nRiesgoH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 153, 40, 28));

        nRiesgoH4.setBackground(new java.awt.Color(255, 255, 255));
        nRiesgoH4.setForeground(new java.awt.Color(0, 0, 0));
        nRiesgoH4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nRiesgoH4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Base.add(nRiesgoH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 153, 40, 28));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        jTextField4.setText("Número de zombis en zonas riesgo");
        jTextField4.setBorder(null);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        Base.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 205, -1, -1));

        nRiesgoZ1.setBackground(new java.awt.Color(255, 255, 255));
        nRiesgoZ1.setForeground(new java.awt.Color(0, 0, 0));
        nRiesgoZ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nRiesgoZ1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Base.add(nRiesgoZ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 199, 40, 28));

        nRiesgoZ2.setBackground(new java.awt.Color(255, 255, 255));
        nRiesgoZ2.setForeground(new java.awt.Color(0, 0, 0));
        nRiesgoZ2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nRiesgoZ2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Base.add(nRiesgoZ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 199, 40, 28));

        nRiesgoZ3.setBackground(new java.awt.Color(255, 255, 255));
        nRiesgoZ3.setForeground(new java.awt.Color(0, 0, 0));
        nRiesgoZ3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nRiesgoZ3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Base.add(nRiesgoZ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 199, 40, 28));

        nRiesgoZ4.setBackground(new java.awt.Color(255, 255, 255));
        nRiesgoZ4.setForeground(new java.awt.Color(0, 0, 0));
        nRiesgoZ4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nRiesgoZ4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Base.add(nRiesgoZ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 199, 40, 28));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        jTextField5.setText("Zombis más letales");
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        Base.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 245, -1, -1));

        Detener.setBackground(new java.awt.Color(255, 255, 255));
        Detener.setForeground(new java.awt.Color(0, 0, 0));
        Detener.setText("Detener Ejecución");
        Detener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetenerActionPerformed(evt);
            }
        });
        Base.add(Detener, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 267, 153, 44));

        ListaZ.setBackground(new java.awt.Color(255, 255, 255));
        ListaZ.setForeground(new java.awt.Color(0, 0, 0));
        ListaZ.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(ListaZ);

        Base.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 267, 186, 69));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void DetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetenerActionPerformed
        try {
            simulacion.togglePausa();
            // Opcional: cambia el texto del botón según el estado
            boolean pausado = simulacion.isPausado();
            Detener.setText(pausado ? "Reanudar ejecución" : "Detener ejecución");
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al pausar/reanudar: " + ex.getMessage());
        }
    }//GEN-LAST:event_DetenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Base;
    private javax.swing.JButton Detener;
    private javax.swing.JList<String> ListaZ;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel nRefugio;
    private javax.swing.JLabel nRiesgoH1;
    private javax.swing.JLabel nRiesgoH2;
    private javax.swing.JLabel nRiesgoH3;
    private javax.swing.JLabel nRiesgoH4;
    private javax.swing.JLabel nRiesgoZ1;
    private javax.swing.JLabel nRiesgoZ2;
    private javax.swing.JLabel nRiesgoZ3;
    private javax.swing.JLabel nRiesgoZ4;
    private javax.swing.JLabel nTunel1;
    private javax.swing.JLabel nTunel2;
    private javax.swing.JLabel nTunel3;
    private javax.swing.JLabel nTunel4;
    // End of variables declaration//GEN-END:variables
}
